# Generated by Django 5.0.3 on 2024-03-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_album_author_book_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_no", models.IntegerField()),
                ("owner", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.vehicle",
                    ),
                ),
                ("car_model", models.CharField(max_length=100)),
            ],
        ),
    ]
