# Generated by Django 5.0.3 on 2024-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_vehicle_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="reg_no",
            field=models.IntegerField(unique=True),
        ),
    ]
